# Site settings
title: 'Marcus Files' # Your Title
tagline: 'A Web Developer. An IT Guy. A wannabe Blogger. A Book Lover.' # A brief tagline for your site
sidebar_image: /images/holmes.jpg

# Build settings
markdown: kramdown
highlighter: rouge
baseurl: 
url: 'http://awesomemarcus.github.io'

author:
  email: marcus.aquiatin@gmail.com
  github: awesomemarcus
  twitter: awesomemarkes
  linkedin: mark-jason-aquiatin-1a193153

# Outputting
permalink: /blog/:title
paginate_path: /blog/page:num/
timezone: null

# Tags settings
# tag_page_layout: tag_page
# tag_page_dir: tag
