# Site settings
title: 'Marcus Files' # Your Title
tagline: 'Web Developer. Blogger' # A brief tagline for your site
sidebar_image: http://annotations.azurewebsites.net/wp-content/uploads/2014/01/holmes.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: 
url: 'http://awesomemarcus.github.io'

author:
  email: marcus.aquiatin@gmail.com
  twitter: awesomemarkes
  linkedin: mark-jason-aquiatin-1a193153

# Outputting
permalink: /blog/:title
paginate_path: /blog/page:num/
timezone: null
