# Site settings
title: 'Marcus Files' # Your Title
tagline: 'Web Developer. Blogger' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: 
url: 'http://awesomemarcus.github.io'

# Outputting
permalink: /blog/:title
paginate_path: /blog/page:num/
timezone: null
