# Site settings
title: 'Marcus Files' # Your Title
tagline: 'Web Developer. Blogger' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: 
url: 'http://awesomemarcus.github.io'

# Outputting
permalink: title
<<<<<<< HEAD
paginate_path: /page:num
timezone: null
=======
>>>>>>> f1d290181d1e04e0182225c17d243bf084638bac
