# Site settings
title: 'Marcus Files' # Your Title
tagline: 'Web Developer. Blogger' # A brief tagline for your site
sidebar_image: /images/holmes.jpg

# Build settings
markdown: kramdown
highlighter: rouge
baseurl: 
url: 'http://awesomemarcus.github.io'

author:
  email: marcus.aquiatin@gmail.com
  github: awesomemarcus
  twitter: awesomemarkes
  linkedin: mark-jason-aquiatin-1a193153

# Outputting
permalink: /blog/:title
paginate_path: /blog/page:num/
timezone: null
